baseURL = 'https://mayabflannery.github.io'
title = 'Maya Breanne Flannery'
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableEmoji = true

# Use pagination.pagerSize instead of 'paginate = 20'
[pagination]
pagerSize = 6

[services]
[services.disqus]
# disqusShortname = "yourdiscussshortname"

[markup]
[markup.highlight]
style = "github-dark"
[markup.goldmark]
[markup.goldmark.parser.attribute]
block = true # for adding css to block (default is false)
[markup.goldmark.renderer]
# If raw html is needed
# unsafe = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
# See: https://gohugo.io/content-management/mathematics/
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]

[params]
author = "Maya B. Flannery"
info = ["PhD Candidate"]
description = "My work"
keywords = "developer,personal,psychology,neuroscience,behaviour,research,cardiac,ppg,music"
avatarurl = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
math = true

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2018

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/mayabflannery"
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin-square fa-2x"
weight = 2
url = "https://www.linkedin.com/in/mayabflannery/"
[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter fa-2x"
weight = 3
url = "https://twitter.com/mayabflannery/"
[[params.social]]
name = ""
icon = "fa fa-building-o fa-2x"
weight = 4
url = "https://beatlab.mcmaster.ca"

# Menu links
[[menu.main]]
name = "About"
weight = 2
url = "about/"
[[menu.main]]
name = "CV"
weight = 2
url = "cv/"
[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"
[[menu.main]]
name = "Posts"
weight = 5
url = "posts/"
[[menu.main]]
name = "Contact"
weight = 4
url = "contact/"
